<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var common\models\SiteSnapshot $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="site-snapshot-form">

    <?php $form = ActiveForm::begin([
    'id' => 'SiteSnapshot',
    'layout' => 'default',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute user_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\User::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('app-model', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
    ]
); ?>

<!-- attribute name -->
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute start_url -->
			<?= $form->field($model, 'start_url')->textInput(['maxlength' => true]) ?>

<!-- attribute count_pages -->
			<?= $form->field($model, 'count_pages')->textInput() ?>

<!-- attribute error404 -->
			<?= $form->field($model, 'error404')->textInput() ?>

<!-- attribute error500 -->
			<?= $form->field($model, 'error500')->textInput() ?>

<!-- attribute redirect300 -->
			<?= $form->field($model, 'redirect300')->textInput() ?>

<!-- attribute duplicates -->
			<?= $form->field($model, 'duplicates')->textInput() ?>

<!-- attribute created_at -->
			<?= $form->field($model, 'created_at')->textInput() ?>

<!-- attribute sitemap_xml -->
			<?= $form->field($model, 'sitemap_xml')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('app-backend', 'SiteSnapshot'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('app-model', 'Create') : Yii::t('app-model', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

