<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "site_snapshot".
 *
 * @property integer $id
 * @property integer $site_project_id
 * @property string $name
 * @property string $start_url
 * @property integer $count_pages
 * @property string $robots_txt
 * @property string $sitemap_xml
 * @property integer $error404
 * @property integer $error500
 * @property integer $redirect300
 * @property integer $duplicates
 * @property string $created_at
 * @property integer $user_id
 *
 * @property \common\models\SiteLog[] $siteLogs
 * @property \common\models\SitePage[] $sitePages
 * @property \common\models\SiteProject $siteProject
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class SiteSnapshot extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'site_snapshot';
    }

    /**
     * @inheritdoc
     * @return \common\models\SiteSnapshotQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\SiteSnapshotQuery(get_called_class());
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'user_id',
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['site_project_id', 'count_pages', 'error404', 'error500', 'redirect300', 'duplicates'], 'integer'],
            [['name', 'start_url'], 'required'],
            [['robots_txt'], 'string'],
            [['created_at'], 'safe'],
            [['name'], 'string', 'max' => 100],
            [['start_url', 'sitemap_xml'], 'string', 'max' => 255],
            [
                ['site_project_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => \common\models\SiteProject::className(),
                'targetAttribute' => ['site_project_id' => 'id']
            ],
            [
                ['user_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => \common\models\User::className(),
                'targetAttribute' => ['user_id' => 'id']
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app-model', 'ID'),
            'site_project_id' => Yii::t('app-model', 'Site Project ID'),
            'user_id' => Yii::t('app-model', 'User ID'),
            'name' => Yii::t('app-model', 'Name'),
            'start_url' => Yii::t('app-model', 'Start Url'),
            'count_pages' => Yii::t('app-model', 'Count Pages'),
            'robots_txt' => Yii::t('app-model', 'Robots Txt'),
            'sitemap_xml' => Yii::t('app-model', 'Sitemap Xml'),
            'error404' => Yii::t('app-model', 'Error404'),
            'error500' => Yii::t('app-model', 'Error500'),
            'redirect300' => Yii::t('app-model', 'Redirect300'),
            'duplicates' => Yii::t('app-model', 'Duplicates'),
            'created_at' => Yii::t('app-model', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteLogs()
    {
        return $this->hasMany(\common\models\SiteLog::className(), ['site_snapshot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSitePages()
    {
        return $this->hasMany(\common\models\SitePage::className(), ['site_snapshot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteProject()
    {
        return $this->hasOne(\common\models\SiteProject::className(), ['id' => 'site_project_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }


}
