<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Body' => '',
    'Create Site Page' => '',
    'Create Site Snapshot' => '',
    'Created At' => '',
    'Delete' => '',
    'ID' => '',
    'Meta Description' => '',
    'Meta Keyword' => '',
    'Name' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Site Page' => '',
    'Site Pages' => '',
    'Site Snapshot' => '',
    'Site Snapshot ID' => '',
    'Site Snapshots' => '',
    'Start Url' => '',
    'Tag H1' => '',
    'The requested page does not exist.' => '',
    'Title' => '',
    'Update' => '',
    'Update Site Page: {nameAttribute}' => '',
    'Update Site Snapshot: {nameAttribute}' => '',
    'Url' => '',
    'User ID' => '',
    'Email Form' => 'Email Form',
    'Log' => 'Лог',
    'Log out' => 'Выход',
    'Message' => 'Сообщение',
    'Phone' => 'Телефон',
    'Profile' => 'Профиль',
    'Queue Manager' => 'Менеджер очереди',
    'Users' => 'Пользователи',
    'Verification Code' => 'Код верификации',
];
