<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error: {code}, Url: {url}' => '',
    'ID' => 'ID',
    'Meta Description' => 'Meta Description',
    'Meta Keyword' => 'Meta Keyword',
    'Name' => 'Название',
    'Params' => 'Параметры',
    'Ping' => 'Ping',
    'Redirect300' => 'Redirect300',
    'Redirect: {code}, Url: {url}' => '',
    'Reindex' => 'Reindex',
    'Relations' => '',
    'Site Project ID' => 'Site Project ID',
    'Site Snapshot ID' => 'Site Snapshot ID',
    'Update Site Page: {nameAttribute}' => '',
    'User ID' => 'User ID',
    'View' => 'Смотреть',
    'Are you sure you want to delete this item?' => '@@@@',
    'Create Site Page' => '@@Создать страницу@@',
    'Create Site Snapshot' => 'Создать снимок',
    'Update Site Snapshot: {nameAttribute}' => 'Изменить снимок {nameAttribute}',
    'Admin' => 'Административное',
    'Are you sure to delete this item?' => 'Точно удалить?',
    'Base Url' => 'Базовый адрес',
    'Body' => 'Body',
    'Cancel' => 'Отмена',
    'Category' => 'Категория',
    'Copy' => 'Копировать',
    'Count Pages' => 'Кол-во страниц',
    'Create' => 'Создать',
    'Created At' => 'Дата создания',
    'Dashboard' => 'Панель управления',
    'Delete' => 'Удалить',
    'Duplicates' => 'Дубликаты',
    'Edit' => 'Редактировать',
    'Email Form' => 'Email Form',
    'Error404' => 'Ошибки 404',
    'Error500' => 'Ошибки 500',
    'First' => 'Первый',
    'Full list' => 'Полный список',
    'General' => 'Главное',
    'Guest' => 'Гость',
    'Last' => 'Крайний',
    'List All' => 'Список всех',
    'Log' => 'Лог',
    'Log out' => 'Выход',
    'Message' => 'Сообщение',
    'New' => 'Создать',
    'Phone' => 'Телефон',
    'Profile' => 'Профиль',
    'Queue Manager' => 'Менеджер очереди',
    'Reset' => 'Сброс',
    'Robots Txt' => 'Robots Txt',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Select' => 'Выбрать',
    'Site Log' => 'Лог сайта',
    'Site Logs' => 'Логи',
    'Site Page' => 'Страница сайта',
    'Site Pages' => 'Страницы сайта',
    'Site Project' => 'Проект сайта',
    'Site Projects' => 'Проекты',
    'Site Snapshot' => 'Снимок сайта',
    'Site Snapshots' => 'Снимки сайта',
    'SiteLog' => 'Лог',
    'SiteProject' => 'Проект',
    'SiteSnapshot' => 'Копия',
    'Sitemap Xml' => 'Sitemap Xml',
    'Start Url' => 'Начальный адрес',
    'Status' => 'Статус',
    'Tag H1' => 'Тэг h1',
    'The requested page does not exist.' => 'Указанная страница не существует',
    'Title' => 'Title',
    'Update' => 'Обновить',
    'Updated At' => 'Дата обновления',
    'Url' => 'Url',
    'User' => 'Пользователь',
    'Users' => 'Пользователи',
    'Verification Code' => 'Код верификации',
    'Welcome' => 'Привет',
];
